import warnings
import winsound
from tkinter import *

from classes import *
from jungcook import *

warnings.filterwarnings('ignore')

# Create your characters here, e.g. Xiao Ming => XIAOMING = NPC("Xiao Ming")
# Already created for you guys, just edit the name if you want
picmain = "pictures/dog.png"
picofJC = "pictures/dog.png"
picofsun = "pictures/dog.png"
picofmoon = "pictures/dog.png"
picofshadow = "pictures/dog.png"
picshadow = "pictures/dog.png"
pic = "pictures/dog.png"
picofgomgom = "pictures/dog.png"
protagonist =  Protagonist("", "")
XIAOMING = NPC("Xiao Ming")
JUNGCOOK = NPC("JungCook")
ADAMCMITH = NPC("Adam Cmith")
JOHNNYSIN = NPC("Johnny Sin")
XM = "Xiao Ming"

DECREASE = "decrease"
INCREASE = "increase"
NEUTRAL = "neutral"
BIGGER = "bigger"
SMALLER = "smaller"

# #[txtImgOptNameSndAff("(After a long and tiring day of classes, school has finally ended...)", "pictures/dog.png", [1]), 
                            # txtImgOptNameSndAff("Damn, I can't believe that it is already 6pm... time to go home and submit my assignment.", "pictures/dog.png", [2], name, "sounds/xm1.wav"),
                            # txtImgOptNameSndAff("(You head for the classroom door, ready to head home...)", "pictures/Mob_Balrog.png", [3]),
                            # txtImgOptNameSndAff("(Suddenly, you felt someone grab your shoulders!)", "pictures/dog.png", [4]),
                            # txtImgOptNameSndAff("NOOO WE ARE GONNA BE LATE, LETS GO NOW!", "pictures/dog.png", [5], "Mia", "sounds/xm2.wav"),
                            # txtImgOptNameSndAff("", "pictures/dog.png", [{"text": "Scene 6", "nextSceneIndex": 6, "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}, {"text": "Scene 7", "nextSceneIndex": 7, "affection": {"affectedNPC": XIAOMING, "change": DECREASE}},{"text": "Neutral 7", "nextSceneIndex": 7, "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}]),
                            # txtImgOptNameSndAff("SCENE 6!", "pictures/dog.png", [], "YAY", "sounds/animalese (1).wav", {"NPC": XIAOMING, "comparison": SMALLER, "amount": 5, "altSceneIndex": 2 }), 
                            # txtImgOptNameSndAff("SCENE 7!", "pictures/dog.png", [4], "YAY", "sounds/animalese (1).wav"),
                            # ]), padx=2, pady=2)

def XIAO_MING(name):
       diag =[
       ["Day 1", picmain, [1]],
       ["After a long and tiring day of classes, school has finally ended.", picmain, [2], "sounds/animalese (1).wav"],
       ["Damn, I can't believe that it is already 6pm...... time to go home and submit my assignment.", picmain, [3], name, "sounds/animalese (1).wav"],
       ["You head for the classroom door, ready to head home.", picmain, [4], name, "sounds/animalese (1).wav"],
       ["Suddenly, you felt someone grabbed your shoulders.", picmain, [5], name, "sounds/animalese (1).wav"],
       ["NOOO WE ARE GONNA BE LATE, LETS GO NOW", picmain, [6], "Mia", "sounds/animalese (1).wav"],
       ["You stare at her, confused.", picmain, [7], "sounds/animalese (1).wav"],
       ["THERES A FOOTBALL MATCH ONGOING, I GOTTA SUPPORT THE BOISSSSSSSSS AND YOUR COMING WITH MEEEEEE!!!", picmain, [8], "Mia", "sounds/animalese (1).wav"],
       ["As much as you are tired, you are just too kind to reject your best friend. Reluctantly, you head towards the football field.....", picmain, [9], "sounds/animalese (1).wav"],
       ["You grudgingly make your way to the stadium", picmain, [10], "sounds/animalese (1).wav"],
       ["You expect the stadium to be filled with cheers and energy.", picmain, [11], "sounds/animalese (1).wav"],
       ["You were wrong.", picmain, [12], "sounds/animalese (1).wav"],
       ["There is an ongoing match, but it's just a scrimmage. There is almost no one watching them except for a few girls “scouting” their potential boyfriends.....", picmain, [13], "sounds/animalese (1).wav"],
       ["Your friend is one of them.", picmain, [], "sounds/animalese (1).wav"],
       ["Fortunately, the scrimmage seems pretty intense. Both teams are even and all players are going all out, desperately trying to take the lead.", picmain, [], "sounds/animalese (1).wav"],
       ["No one seem to stand out....except one.", picmain, [], "sounds/animalese (1).wav"],
       ["You see a tall, charming and muscular guy with spiky hair intercepting a pass.", picmain, [], "sounds/animalese (1).wav"],
       ["He dribbles the ball up gracefully and strikes a powerful shot into goal with ease.", picmain, [], "sounds/animalese (1).wav"],
       ["For the rest of the match, you had your eyes on him the entire time, being absolutely impressed by his skills and presence on the field.", picmain, [], "sounds/animalese (1).wav"],
       ["Guys!! The game isn’t over, protect the lead. Keep it up till the whistle!!", picmain, [], "The Guy", "sounds/animalese (1).wav"],
       ["He seems to give off such an energetic and fearsome aura over the whole field.... you could feel it all the way at the stands.", picmain, [], "sounds/animalese (1).wav"],
       ["He must be really passionate about the game... after all it’s just a scrimmage.", picmain, [], name, "sounds/animalese (1).wav"],
       ["I wonder what class he is from.....", picmain, [], name, "sounds/animalese (1).wav"],
       ["The game ends, Mia drags you back towards dorm while rumbling about how cool her crush was in the field.", picmain, [], name, "sounds/animalese (1).wav"],
       ["None of the conversation entered your head.... as the passionate spiky hair boy you witnessed earlier is stuck on your mind.", picmain, [], "sounds/animalese (1).wav"],
       # DAY 2
       ["It’s 3pm. Lesson just ended and you decide to grab a quick late lunch in the canteen.", picmain, [], "sounds/animalese (1).wav"],
       ["Its pretty late... I hope there is not many people in the canteen at this time.", picmain, [], name, "sounds/animalese (1).wav"], 
       ["You enter the canteen.", picmain, [], "sounds/animalese (1).wav"], 
       ["To your relief, there is almost no one in the canteen..... but someone catches your attention.", picmain, [], "sounds/animalese (1).wav"],
       ["You notice the spiky hair dude that was on your mind last night.", picmain, [], "sounds/animalese (1).wav"],
       ["He is sitting at the very corner of the canteen, having his own meal.", picmain, [], "sounds/animalese (1).wav"],
       ["You saw the great opportunity and mustered up your courage, approaching him with slight nervousness.", picmain, [], "sounds/animalese (1).wav"],
       ["Hey...?", picmain, [], name, "sounds/animalese (1).wav"],
       ["hello.....uhhh....do I know you?", picmain, [], "?", "sounds/animalese (1).wav"], #nervous
       ["Hi! I am {}. I was at the scrimmage yesterday. You were amazing out there! Mind if I join you?".format(name), picmain, [], name, "sounds/animalese (1).wav"],
       ["Oh, um, sure. I guess.", picmain, [], "?", "sounds/animalese (1).wav"], #surprised
       ["You ask for his name. He very shyly tells you that his name is Xiao Ming.", picmain, [], "sounds/animalese (1).wav"],
       ["You can tell that he is super shy and introverted.....maybe even socially awkward.", picmain, [], "sounds/animalese (1).wav"], 
       ["He acts completely different from when he was playing in the field yesterday.", picmain, [], "sounds/animalese (1).wav"], 
       ["I've been meaning to ask, what's the story behind your incredible moves on the field? Are you self-taught, or did you have a coach?", picmain, [], name, "sounds/animalese (1).wav"],
       ["Well..... my dad played a bit back in the day. He taught me the basics, and I guess the rest just kind of came naturally.", picmain, [], XM, "sounds/animalese (1).wav"], #shy
       ["That's amazing! It must be great having that connection with your dad. How long have you been playing football for? You seemed to be a beast out on the field last night.", picmain, [], name, "sounds/animalese (1).wav"],
       ["As XM gradually opened up about his love for the sport, Me discovered more about the person behind the athlete.", picmain, [], "sounds/animalese (1).wav"],
       ["The more you listen, the more charmed you are.", picmain, [], "sounds/animalese (1).wav"],
       ["You found the contrast between his shy demeanour and his ferocious game-time energy to be really cute. After all, how can someone be as fierce as a tiger one moment and super shy and awkward in the next?", picmain, [], "sounds/animalese (1).wav"], 
       ["He doesn’t even dare to look into your eyes while speaking...", picmain, [], "sounds/animalese (1).wav"],
       ["I noticed you seem really in the zone when you play. Is there a specific routine you follow before a game?", picmain, [], name, "sounds/animalese (1).wav"],
       ["Not really, just a bit of stretching and listening to some calming music. Helps me focus.", picmain, [], XM, "sounds/animalese (1).wav"], 
       ["Despite his reserved nature, Me sensed a hidden passion within XM.", picmain, [], "sounds/animalese (1).wav"],
       ["You know, XM, you're not at all what I expected.", picmain, [], name, "sounds/animalese (1).wav"],
       ["What did you expect?", picmain, [], XM, "sounds/animalese (1).wav"], #shy
       #("", picofsun, [{"text": "Act SUS", "nextSceneIndex": 19, "affection": {"affectedNPC": JUNGCOOK, "change": INCREASE}}, {"text": "Ignore him", "nextSceneIndex": 24, "affection": {"affectedNPC": JUNGCOOK, "change": NEUTRAL}}, {"text": "Act Curious", "nextSceneIndex": 26, "affection": {"affectedNPC": JUNGCOOK, "change": DECREASE}}]) 
       ["", picmain, [{"text": "I don't know, maybe someone more... distant. But you're surprisingly easy to talk to.", "nextSceneIndex": 52, "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}, {"text": "You seemed to be more conservative and shy, especially after seeing your energy and passion out on the field last night", "nextSceneIndex": 54, "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}, {"text": "You seemed to be more conservative and shy, especially after seeing your energy and passion out on the field last night.", "nextSceneIndex": 55, "affection": {"affectedNPC": XIAOMING, "change": DECREASE}}]],
       ["….Ahhh thanks a lot for that! I am aware I am quite socially awkward... but hearing someone say that I am approachable and easy to talk to sure is nice!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["I will keep improving ok!!", picmain, [56], XM, "sounds/animalese (1).wav"],
       ["yeahh..... I get that a lot. I just don’t have a lot of energy in me unless I am playing football.... hope that’s ok.", picmain, [56], XM, "sounds/animalese (1).wav"],
       ["ohhh mannn.... I know I can be pretty awkward at times. Sorry if I wasn’t able to match your energy... I will keep trying......", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(You continue the small talks with him and gained a deeper understanding of his character.) " , picmain, [], "", "sounds/animalese (1).wav"],
       ["(Despite being shy and awkward, Xiao Ming seems to be equally interested in you as well. At least it seems that he is happy to share his stories to you.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You even managed to exchange contacts with him, making a promise to meet each other again at some point.)" , picmain, [], "", "sounds/animalese (1).wav"],
       ["(You head back to dorm with a huge smile on your face... perhaps it is the start of something you have been looking for......)" , picmain, [], "", "sounds/animalese (1).wav"],
       # DAY 3-----------------------------------
       ["(There is no lessons today as it is Wednesday.)" , picmain, [], "", "sounds/animalese (1).wav"],
       ["(You realised that you have plenty of assignments uncompleted.)" , picmain, [], "", "sounds/animalese (1).wav"],
       ["wow there is so much homework...physics, maths, ctd, and hass. It never ends zzzzzz....", picmain, [], name, "sounds/animalese (1).wav"],
       ["(Trying to find a chance to meet XM, you invite him to study together in the library.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["How about tackling some assignments together? Two heads are better than one!" , picmain, [], name, "sounds/animalese (1).wav"],
       ["Uh, sure. I usually study alone, though." , picmain, [], XM, "sounds/animalese (1).wav"],
       ["", picmain, [{"text": "Why not give it a go? Who knows, you might find it more productive too!! If you run into a tough question, we can help each other out.", "nextSceneIndex": 75, "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}, {"text": "Ahh I see. Do you wanna try it out though? It can potentially be more productive :D .", "nextSceneIndex": 75, "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}, {"text": "I understand, group studying might be for everyone.", "nextSceneIndex": 67, "affection" : {"affectedNPC": XIAOMING, "change": DECREASE}}]],
       ["Totally cool if it’s not your style, I shouldn’t disturb you.", picmain, [], name, "sounds/animalese (1).wav"],
       ["...yeah I am sorry, I realise that I am only productive when by myself so...", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Being disappointed, you are about to just say goodbye and move on. However, before you have the chance to end the conversation, he says something that is quite surprising.)", picmain, [], "", "sound/animalese (1).wav"],
       ["hey, maybe we can’t really study together... BUT how about we get dinner tomorrow to make up for it", picmain, [], XM, "sound/animalese (1).wav"],
       ["(That caught you off guard.)", picmain, [], "", "sound/animalese (1).wav"],
       ["uhhhh sure!! I am totally down for it!! See you tomorrow then!", picmain, [], name, "sound/animalese (1).wav"],
       ["(That made your day.)", picmain, [], "", "sound/animalese (1).wav"],
       ["(You spend the whole day by yourself in the library, fully motivated and positive knowing that you will be able to see him the next day anyways.)", picmain, [96], "", "sound/animalese (1).wav"],
       ["Sure, that sounds good. Teamwork might make this less daunting.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(The library becomes a haven of shared knowledge as you both delve into your assignments. XM surprises you with his insightful contributions.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Thanks for your heIp. I wouldn't have figured that out on my own", picmain, [], XM, "sounds/animalese (1).wav"],
       ["No problem at all! We make a great team. What do you say we celebrate a productive day with some ice cream? My treat.", picmain, [], name, "sounds/animalese (1).wav"],
       ["Ice cream sounds nice. Sure.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Great! Let's head to Pick-And-Go. They have a really solid selection of flavours!!", picmain, [], name, "sounds/animalese (1).wav"],
       ["(After a dreadful series of assignments, both of you went to grab some ice-cream for a well-deserved treat.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Not bad. We managed to complete our homework!! Do you always study in the library?", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Mostly, yeah. It's a good atmosphere for me. How about you? Any specific study rituals or habits?", picmain, [], name, "sounds/animalese (1).wav"],
       ["Not really. I just try to stay focused. Do you have any tips for staying organized?", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Oh, absolutely! I'm a fan of color-coded notes and setting small goals. Keeps things manageable. What's your approach?", picmain, [], name, "sounds/animalese (1).wav"],
       ["I keep a checklist and try to cross things off as I go. It helps me see my progress.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Nice! A checklist can be really satisfying, I should try doing that.", picmain, [], name, "sounds/animalese (1).wav"],
       ["(You really enjoyed the study session.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Craving to see him again soon, you muster up your courage.)", picmain, [], name, "sounds/animalese (1).wav"],
       ["I really enjoyed studying with you today!!", picmain, [], name, "sounds/animalese (1).wav"],
       ["Let’s...... hang out again tomorrow!! How about dinner at Changi City Point?", picmain, [], name, "sounds/animalese (1).wav"],
       ["(He seems a little shocked by the sudden request.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(He shyly smiles.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["uhhh.....I should be free tomorrow...I....I think....", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(As you part ways with him, you gleefully smile all the way back to dorm, excited about tomorrow.)", picmain, [], "", "sounds/animalese (1).wav"],
       # DAY 4 ------------------- 
       ["(It is approaching the dinner.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Feeling very excited, you put on your favourite outfit and perfume.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You set off the CCP to meet him)", picmain, [], "", "sounds/animalese (1).wav"],
       ["hey, you look great today.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Your heart flutters.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["hahahaha thanks!! Uhhhh what do you wanna eat today?", picmain, [], name, "sounds/animalese (1).wav"],
       ["Honestly, I am clueless about the restaurants here...what are your recommendations?", picmain, [], XM, "sounds/animalese (1).wav"],
       ["", picmain, [{"text": "ohhh, I am kinda craving for some Japanese food!! How about Suki-ya? It’s pretty value-for-money.", "nextSceneIndex": 109, "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}, {"text": "hmmm, how about MacDonalds? I have cravings for some delicious McSpicy.", "nextSceneIndex": 107, "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}, {"text": "hmmm, how about Shabu Sai, I am really craving some free-flow hotpot buffet right now!!", "nextSceneIndex": 104 , "affection": {"affectedNPC": XIAOMING, "change": DECREASE}} ]],
       ["Wow that’s gonna be quite the burden on my wallet. Can we keep it simple? After all it’s just a normal dinner", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Oof, that sounded sad)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Ahhh that’s fine, how about Suki-ya instead? It pretty budget compared to the others.", picmain, [109], name, "sounds/animalese (1).wav"],
       ["ahhh sorry but I am trying to avoid fast food currently, I have got a competition coming up and am trying my best to stay healthy.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Oh that’s fair, how about Suki-ya then. There is a huge selection of food that is not fried and its quite budget friendly too!", picmain, [], name, "sounds/animalese (1).wav"],
       ["That sounds nice... lets go for it.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Both of you enter the restaurant and get seated.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(After placing your orders, it’s time to learn even more about each other.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["", picmain, [{"text": "Hey, I know that you are passionate about sports. Do you happen to watch the NBA? I am a huge fan too!!", "nextSceneIndex": 117 , "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}, {"text": "Uhh.... so what are your hobbies other than football?", "nextSceneIndex": 118 , "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}, {"text": "(Be silent and stare into his beautiful eyes awkwardly.... (you’re too nervous!!))", "nextSceneIndex": 113 , "affection": {"affectedNPC": XIAOMING, "change": DECREASE}}]],
       ["(As expected of a super shy and introverted guy, XM stares back at you, equally awkward)", picmain, [], "", "sound/animalese (1).wav"],
       ["(You want to initiate a conversation, but you are so tense and nervous to think of a topic.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Both of you eat the meal in silence.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(The miserable night ends like this... shame on you LOL)", picmain, [127], "", "sounds/animalese (1).wav"],
       ["(XM eyes lit up.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["I love watching the NBA!! I always watch them.... even in class hehe.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["My favourite team is the Celtics!! I am a super huge fan of Jason Tatum, what about you?", picmain, [], XM, "sounds/animalese (1).wav"],
       ["DAMN I am SOO glad that you enjoy watching the NBA!! I am a hardcore fan and it’s nice that we have something in common 😊", picmain, [], name, "sounds/animalese (1).wav"],
       ["I am a big fan of the Warriors!! Always been a joy to watch Steph Curry play the game, he really changed the entire NBA scene with his 3-pointers.", picmain, [], name, "sounds/animalese (1).wav"],
       ["(Both of you seemed to have found a common interest.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Even when the food arrived, both of you continued to discuss about the sport, from the performance of each team and even predictions for the champion this season.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You both clown at some under-performing players and laugh at NBA memes together.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Suddenly it feels like both of you have gotten super close as the ‘friendship’ continues to deepen.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You wish for the conversation to continue forever, but of course all good things must come to an end.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(After dinner, you both head to dorm together with all smiles, looking forward to the next meeting...)", picmain, [], "", "sounds/animalese (1).wav"],
       # DAy 5 ------------- end at [127]
       ["(The previous night, both of you agreed to meet up again today.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(This time, you meet Xiao Ming at the outdoor basketball court.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Turns out, after learning that both of you have a keen interest in NBA and basketball in general, you take the opportunity to ask him out to play basketball with you.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(When you reach the court, he is already shooting around by himself.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Heyyy!! Let’s shoot the ball together.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(He passes you the ball and you throw up a few shots at the hoop.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(…..you completely miss the target multiple times.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You look super embarrassed, getting ready to be clowned upon by XM.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(However, he kindly smiles and didn’t seem to be judgemental at all.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hahaha it’s ok, let me teach you how to shoot the ball. There is certain techniques involved in shooting.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(He starts going through the shooting motion with you.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["First, you have to make sure only your shooting hand interferes with the shot... your guide hand should not alter the path of the shot at all", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Also, be sure to flick your wrist. Imagine that you are dipping your fingers into the hoop as you shoot. Hold the follow through too!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(He passes you the ball again, signalling for you to give it a shot.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Unfortunately, you just seem to suck at the game.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Rather than laughing at you, he walks towards you.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(He holds your hand, places the ball on your palm.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(He starts to personally adjust your shooting posture with his hands.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You feel your heart beating fast.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You unconsciously look into his eyes.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(His gentle eyes gazes back into your soul.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You maintain eye contact with him by accident, feeling adrenaline surging through your body)", picmain, [], "", "sounds/animalese (1).wav"],
       ["", picmain, [{"text": "Continue holding that eye contact 😉", "nextSceneIndex": 151 , "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}, {"text": "Step away from embarrassment.", "nextSceneIndex": 154 , "affection": {"affectedNPC": XIAOMING, "change": DECREASE}}, {"text": "Look away shyly", "nextSceneIndex": 156, "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}]],
       ["ahhh sorry!!", picmain, [], XM, "sounds/animalese (1).wav"], #150
       ["(He shyly looks away, returning to his typical shy state.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["uhh uhhh but ye...ahhh!! This is how the posture should be!!", picmain, [156], XM, "sounds/animalese (1).wav"],
       ["(He looks apologetic.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey, im so sorry, should have respected your personal space.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["I will be more mindful alright?", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Anyways, there you have it. Practice shooting with this posture and you will be a sharpshooter in no time!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(You take another shot, following the shooting posture given.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You score.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["LETS GO!! Damn your advice is amazing!!", picmain, [], name, "sounds/animalese (1).wav"],
       ["Yeah I know right!! I am sure you will be solid in no time!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(After the session, y’all head back to dorm together)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey, that was fun, thanks so much for all the guidance, really appreciate it!!", picmain, [], name, "sounds/animalese (1).wav"],
       ["It’s not just me, you are a really fast-learner! It took me way longer to be able to shoot the ball decently", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Y’all part ways, with the plans of catching a movie tomorrow since it is the weekends.)", picmain, [], "", "sounds/animalese (1).wav"],
       # DAY 6 end at [164]
       ["(It’s finally the weekends.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You happily make your way to Century Square, getting ready to meet Xiao Ming for a cute movie date.)", picmain, [], "", "sounds/animalese (1).wav", {"NPC": XIAOMING, "comparison": SMALLER, "amount": 3, "altSceneIndex": 193}],
       ["(You reach the cinema and already spotted XM waiting at the corner. )", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Being happy that he is very punctual, you walk up to him enthusiastically)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey, thank for being on time!!", picmain, [], name, "sounds/animalese (1).wav"],
       ["No problem. So, what movies do you want to watch?", picmain, [], XM, "sounds/animalese (1).wav"],
       ["", picmain, [{"text": "I am thinking of watching a horror!! The Nun sounds thrilling to watch!!", "nextSceneIndex": 176 , "affection": {"affectedNPC": XIAOMING, "change": INCREASE }}, {"text": "How about some comedy? I really need a good laugh to end off this stressful week.", "nextSceneIndex": 175 , "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}, {"text": "How about a romance movie? I have been looking forward to watch “A Silent Voice” in the cinemas.", "nextSceneIndex": 173, "affection": {"affectedNPC": XIAOMING, "change": DECREASE}}]],
       ["ahhhh...... romance are not really my kinda thing. I have always been into something action-packed and thrilling. Love the adrenaline rush these movies give me. Let’s watch The Nun instead shall we? It should be exciting.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Okok, let’s do it.", picmain, [176], name, "sounds/animalese (1).wav"],
       ["Comedy sounds nice, however I am lowkey craving for something thrilling. Let’s watch The Nun instead.", picmain, [176], XM, "sounds/animalese (1).wav"],
       ["”Damn you actually read my mind!! I am a huge fan of horror movies too. Let’s do it.”", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(After buying tickets and some popcorns, you both head into the cinema and got seated.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(As expected, the movie was gruesome and filled with jumpscares.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You hold on for your dear life.... maybe such movies are not meant for you.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(XM seems to notice your uneasiness.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(At the climax of the movie, you felt him squeezing your hands.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Perhaps it’s to comfort you.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["", picmain, [{"text": "Pretend nothing happen ;)", "nextSceneIndex": 183 , "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}, {"text": "Move your hand away.", "nextSceneIndex": 186 , "affection": {"affectedNPC": XIAOMING, "change": DECREASE}}]],
       ["(You sit through the remaining of the movie like this.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Your heart beats fast... not because of the horror but rather from Xiao Ming’s actions.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(After what seems like forever, the movie ends.)", picmain, [188], "", "sounds/animalese (1).wav"],
       ["(XM also quickly withdraws his hand, looking flustered.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Both of you watch the remaining of the movie awkwardly with no further interactions)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Wow!! That sure was thrilling!! How did you find it? You seemed pretty horrified haha.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Yeah, that was really scary, maybe I overestimated myself.", picmain, [], name, "sounds/animalese (1).wav"],
       ["Hahahaha its okay, you look pretty cute when scared anyways.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(You blush.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["uhhhh anyways, I got to go now, see you tomorrow!!", picmain, [], XM, "sounds/animalese (1).wav"],
       # alt scene last line [192]
       ["(You arrive at the mall and started waiting for him.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["hmmm....he said to meet at 10am, he is 10 minutes late. Why isn’t he here yet", picmain, [], name, "sounds/animalese (1).wav"],
       ["Maybe I should give him a call", picmain, [], name, "sounds/animalese (1).wav"],
       ["(You call him.... but there was no response.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["damn, lets just wait a while more.", picmain, [], name, "sounds/animalese (1).wav"],
       ["(As time goes by.... you become more and more infuriated.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You look at the time, it’s 10.40am now.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Finally, you receive a call from him)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey!! Where are you? It’s already 10.40am!! We will probably have to catch the next movie timing!", picmain, [], name, "sounds/animalese (1).wav"],
       ["Yo, I am soooooo sorry, but something came up at home and I can’t join you today anymore", picmain, [], XM, "sounds/animalese (1).wav"],
       ["", picmain, [{"text": "Hey, if it’s a family emergency or something, don’t sweat about it. I understand. I hope everything’s ok at home.", "nextSceneIndex": 204 , "affection": {"affectionNPC": XIAOMING, "change": INCREASE}}, {"text": "It’s cool. It’s just that you should have told me in advance if you couldn’t make it.", "nextSceneIndex": 206, "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}, {"text": "WTF, you can’t just make me wait for 40 damn minutes just for you to say that you can’t make it!!", "nextSceneIndex": 207, "affection": {"affectedNPC": XIAOMING, "change": DECREASE}}]],
       ["Hey, if it’s a family emergency or something, don’t sweat about it. I understand. I hope everything’s ok at home.", picmain, [], name, "sounds/animalese (1).wav"],
       ["Thanks for understanding!! I am genuinely sorry and I will do my best to make it up to you!!", picmain, [208], XM, "sounds/animalese (1).wav"],
       ["My bad. I will make sure it won’t ever happen again.", picmain, [208], XM, "sounds/animalese (1).wav"],
       ["Yoooo I am so sorry, it’s totally my bad. I hope you don’t get mad. I promise I will make it up to you. Calm down alright?", picmain, [], XM, "sounds/animalese (1).wav"],
       ["How about meeting again tomorrow? Same time. I swear that I won’t make you wait for me anymore!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Disappointed, you head back home)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(It sucks, but at least he promises to make it up to you tomorrow, so your hopes are still alive.)", picmain, [], "", "sounds/animalese (1).wav"],
       # LAST DAY FINALLY [210]
       ["(Before meeting Xiao Ming, you plan to get a gift for him for no particular reason.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Maybe love makes you do dumb things.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Hmmm, what should I get?)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(In the afternoon, you meet up with XM at the shopping mall.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey!! I brought you a lil something, hope you like it!!", picmain, [], name, "sounds/animalese (1).wav"],
       ["(You hand him the gift.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["What gift did you buy for him?", picmain, [], "", "sounds/animalese (1),wav"],
       ["", picmain, {"text": "A shoebag", "nextSceneIndex": 219, "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}, {"text": "A bunch of snacks.", "nextSceneIndex": 220, "affection": {"affectedNPC": XIAOMING, "change": NEUTRAL}}, {"text": "A cute phone cover", "nextSceneIndex": 221, "affection": {"affectedNPC": XIAOMING, "change": DECREASE}}],
       ["Wait.... how did you know I needed this, my old shoebag got holes in it and I was planning to replace it. This will do it for me!! Thanks so much!!", picmain, [222], XM, "sounds/animalese (1).wav"],
       ["Oohhhh thanks!! This will push me through the late night studies!!", picmain, [222], XM, "sounds/animalese (1).wav"],
       ["Ahh shit, my phone doesn’t fit into the cover 🙁 I appreciate it a lot though.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(You start walking around the shopping mall.)", picmain, [231], "", "sounds/animalese (1).wav", {"NPC": XIAOMING, "comparison": BIGGER, "amount": 4, "altSceneIndex": 227}],
       ["(XM also takes out something from his bag.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey, I brought something as well. I am not sure if you are a fan of cute key-chains, but I came across it and thought that it suits you well!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(He passes you a cute rabbit keychain.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You feel very heartened that he brought you a gift too.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Soooo... where do you wanna shop at?", picmain, [], XM, "sounds/animalese (1).wav"],
       ["", picmain, [{'text': "Sephora", "nextSceneIndex": 229, "affection": {"affectedNPC": XIAOMING, "change": DECREASE}}, {"text": "Victoria's Secret (are you fr?)", "nextSceneIndex": 229, "affection": {"affectedNPC": XIAOMING, "change":DECREASE}}, {"text": "Foot-Locker", "nextSceneIndex": 231, "affection": {"affectedNPC": XIAOMING, "change": INCREASE}}]],
       ["uhhhh... ngl I personally wouldn’t get anything from there anyways. How about Foot Locker instead? I wanna scout some new shoes to add to my collection!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Ohh sounds good. I don’t mind looking at some nice shoes too.", picmain, [232], name, "sounds/animalese (1).wav"],
       ["Yooo, I didn’t know that you are into shoes, I am a sneakerhead too!! If you’re looking to get a new shoe I am down to recommend you some a few models", picmain, [], XM, "sounds/animalese(1).wav"],
       ["(Both of you visit Foot Locker, XM passionately goes through all the models of the shoes being displayed.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(He recommends a few pair that he personally thinks are value-for-money.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Here, try these few pairs. It’s durable, comfortable and looks great aesthetically at the same time!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(You try on the shoes.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["“Hey, you look amazing with this!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Embarassed but thrilled by the compliment, you decide to purchase the pair of shoes. After all, you actually like it too.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Seeing you buy the shoes he recommended, he smiles ear to ear, perhaps it was the satisfaction from successfully recommending a pair of shoes he likes too. )", picmain, [], "", "sounds/animalese (1).wav"],
       ["(After shopping, both of you decide to stop by the arcade)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Let’s play the basketball machine!! It’s my favourite game in the arcade.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(At the basketball machine, you pick up the ball.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You adopt the shooting stance he taught you a few days back.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(He seems to notice it and smiles proudly.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Wow, you seem to absorb everything I taught you!! You are such a fast learner!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Both of you decide to have a friendly battle of points, with the loser treating dinner.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Clearly, you lost the battle.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Aw man, I guess dinner is on me.", picmain, [], name, "sounds/animalese (1).wav"],
       ["All’s good, a drink will be fine. It was intense for sure. Close game, GGs!!", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(After treating him to bubble tea, both of you decide to take a stroll in the nearby park to end the day.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Making full use of this golden opportunity, you muster up your courage.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey.... you know about prom at the end of the term right?", picmain, [], name, "sounds/animalese (1).wav"],
       ["Yeah... what about it", picmain, [], XM, "sounds/animalese (1).wav"],
       ["I....I was thinking if you can go to prom with me.", picmain, [], name, "sounds/animalese (1).wav"],
       ["(XM stops in his tracks. He seemed visibly shocked)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(He seems to be processing what you said.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(After all, it was quite sudden.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You hold your breath, suddenly not feeling confident about this.)", picmain, [], "", "sounds/animalese (1).wav", {"NPC": XIAOMING, "comparison": SMALLER, "amount": 4, "altSceneIndex": 266}], #[257]
       ["(Thankfully, his shocked face slowly turns into a heartwarming gentle smile.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey.... how can I possibly say no to this beautiful girl here! Of course I want to.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["It’s just that...I was taken aback. I was planning to ask you out for prom at some point too. I was just too shy to bring it up.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["Thank god you initiated it, now I don’t have to do it myself HAHA", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Congrats, it seems like the feelings was mutual.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(On high spirits, both of you treasure the stroll back to the MRT station with all laughs and giggles.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(Even on the way home, you smile uncontrollably.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You now have to motivation to push through the arduous studying, knowing that when exams are over you get to go prom with him.)", picmain, [500], "", "sounds/animalese (1).wav"],
       ["(His face turned into a small frown. )", picmain, [], "", "sounds/animalese (1).wav"],
       ["Hey, I am so sorry if I made you misunderstood.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["I have always just seen you as a nice friend right from the beginning.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["I actually have someone else in mind.", picmain, [], XM, "sounds/animalese (1).wav"],
       ["(Your heart completely sank.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["I understand.... guess I was just overthinking things.", picmain, [], name, "sounds/animalese (1).wav"],
       ["Sorry for misunderstanding your actions...", picmain, [], name, "sounds/animalese (1).wav"],
       ["(Filled with embarrassment, you couldn’t wait to escape.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["I have something on.... I gotta go now.", picmain, [], name, "sounds/animalese (1).wav"],
       ["(You turn around and sprinted all way to the MRT station without even saying goodbye.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["You start sobbing all the way home.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["(You got friendzoned.)", picmain, [], "", "sounds/animalese (1).wav"],
       ["Maybe it was just not meant to be.....", picmain, [], "", "sounds/animalese (1).wav"]
       ]
       

    
       
       

       
       

       return diag